### ISSUE TITLE
any possible for reference-free for WGBS?

### ISSUE THREAD

**Issue by xflicsu** [thomasvangurp/epiGBS#2]
Hello Thomas,
        Your software provide a new view about DNA methylation analysis.
        My question is as the question asked in title.
        Reference-free of WGBS would extend our view of both genetics and epigenetics.
Best,

**Comment by thomasvangurp** [comment]
Hi Xianfeng,

This would be possible, but you would have to ‘tag' watson and crick molecules by means of an adapter containing unmethylated cytosines that provide a recognition option for said strands. Furthermore, high library complexity would impede this process, as in order to reconstruct the reference sequence for a fragment the watson AND crick strand from the same molecule would have to be sequenced. I think that a hairpin adapter connecting both strands might work better. Even if you can reconstruct the reference of the molecule, you would still need to ‘connect’ these molecules together.

Kind regards,
Thomas

Van:  Xianfeng Li <notifications@github.com>
Beantwoorden - Aan:  thomasvangurp/epiGBS <reply@reply.github.com>
Datum:  maandag 22 februari 2016 04:45
Aan:  thomasvangurp/epiGBS <epiGBS@noreply.github.com>
Onderwerp:  [epiGBS] any possible for reference-free for WGBS? (#2)


Hello Thomas,
 Your software provide a new view about DNA methylation analysis.
 My question is as the question asked in title.
 Reference-free of WGBS would extend our view of both genetics and epigenetics.
Best,
